### ISSUE TITLE
Hi, N3tc4t, whats the password of admin?

### ISSUE THREAD

**Issue by AndyXGWang** [N3TC4T/Hotel-Management-System-#1]
Hi,

I have try the CI Hotel system offline and can't login with admin admin.

what's the password?

thanks

**Comment by AndyXGWang** [comment]
I just change the member model file and login system. tks

**Comment by N3TC4T** [comment]
Hey
for login use this :
admin:guards

**Comment by SabanMishriya** [comment]
hi sir login and other things are not opening , i am running first time but didn't load the page please can you help me  my email id is saban313@gmail.com
